const {contextBridge, ipcRenderer} = require('electron');
contextBridge.exposeInMainWorld('amber', {
  profiles:()=>ipcRenderer.invoke('profiles:list'),
  copy:text=>ipcRenderer.invoke('clipboard:write',text),
  settings:()=>ipcRenderer.invoke('settings:get'),
  font:size=>ipcRenderer.invoke('settings:font',size),
  commandsSave:commands=>ipcRenderer.invoke('commands:save',commands),
  commandsRun:(id,commandId)=>ipcRenderer.invoke('commands:run',id,commandId),
  exportProfiles:()=>ipcRenderer.invoke('profiles:export'),
  importPreview:()=>ipcRenderer.invoke('profiles:import-preview'),
  importApply:(token,accepted)=>ipcRenderer.invoke('profiles:import-apply',token,accepted),
  sftpList:(id,path)=>ipcRenderer.invoke('sftp:list',id,path),
  sftpUpload:(id,path)=>ipcRenderer.invoke('sftp:upload',id,path),
  sftpDownload:(id,path)=>ipcRenderer.invoke('sftp:download',id,path),
  sftpCancel:id=>ipcRenderer.invoke('sftp:cancel',id),
  save:(profile,secrets)=>ipcRenderer.invoke('profiles:save',profile,secrets),
  remove:id=>ipcRenderer.invoke('profiles:remove',id),
  key:()=>ipcRenderer.invoke('key:choose'),
  connect:(id,secrets,size,resumeId)=>ipcRenderer.invoke('ssh:connect',id,secrets,size,resumeId),
  disconnect:(id,forget)=>ipcRenderer.invoke('ssh:disconnect',id,forget),
  root:id=>ipcRenderer.invoke('ssh:root',id),
  answer:(id,accepted)=>ipcRenderer.invoke('dialog:answer',id,accepted),
  input:(id,data)=>ipcRenderer.send('ssh:input',id,data),
  resize:(id,cols,rows)=>ipcRenderer.send('ssh:resize',id,cols,rows),
  window:action=>ipcRenderer.send('window:action',action),
  onEvent:callback=>{ const handler=(_event,value)=>callback(value); ipcRenderer.on('ssh:event',handler); return ()=>ipcRenderer.removeListener('ssh:event',handler); }
});
