import {useEffect,useRef,useState} from 'react';
import {X,Search,Plus,Pencil,Trash2,Play,Folder,File,ArrowUp,Download,Upload,RefreshCw,Link} from 'lucide-react';
export type QuickCommand={id:string;name:string;command:string};
export type ServerProfile={id:string;name:string;host:string;username:string};
function Modal({title,onClose,children,className=''}:{title:string;onClose:()=>void;children:React.ReactNode;className?:string}){
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('input,textarea,button')?.focus();return()=>previous?.focus();},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className={`modal feature-modal ${className}`} role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{
    if(e.key==='Escape'){e.stopPropagation();onClose();}
    if(e.key==='Tab'){const items=[...ref.current!.querySelectorAll<HTMLElement>('input,textarea,button:not(:disabled)')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
  }}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="Закрыть окно" onClick={onClose}><X size={18}/></button></div>{children}</div></div>;
}
export function ServerPalette({profiles,onConnect,onClose}:{profiles:ServerProfile[];onConnect:(id:string)=>void;onClose:()=>void}){
  const [query,setQuery]=useState(''),[selected,setSelected]=useState(0);
  const matches=profiles.filter(p=>`${p.name} ${p.host} ${p.username}`.toLowerCase().includes(query.toLowerCase()));
  useEffect(()=>setSelected(0),[query]);
  function choose(id:string){onClose();onConnect(id);}
  return <Modal title="Быстрое подключение" onClose={onClose} className="server-palette"><div className="palette-search"><Search size={17}/><input autoFocus aria-label="Найти подключение" placeholder="Название, адрес или пользователь" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Enter'].includes(e.key)){e.preventDefault();if(e.key==='Enter'){if(matches[selected])choose(matches[selected].id);}else setSelected(i=>matches.length?(i+(e.key==='ArrowDown'?1:-1)+matches.length)%matches.length:0);}}}/></div><div className="palette-list">{matches.map((p,i)=><button className={i===selected?'chosen':''} key={p.id} onMouseEnter={()=>setSelected(i)} onClick={()=>choose(p.id)}><strong>{p.name}</strong><small>{p.username}@{p.host}</small></button>)}{!matches.length&&<p className="feature-empty">{profiles.length?'Ничего не найдено':'Сначала добавьте сервер'}</p>}</div><p className="feature-hint">↑ ↓ выбрать · Enter подключиться · Esc закрыть</p></Modal>;
}
export function Commands({commands,connected,onSave,onRun,onClose}:{commands:QuickCommand[];connected:boolean;onSave:(commands:QuickCommand[])=>Promise<string|undefined>;onRun:(id:string)=>void;onClose:()=>void}){
  const [draft,setDraft]=useState<QuickCommand|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function save(next:QuickCommand[]){setBusy(true);const message=await onSave(next);setBusy(false);setError(message||'');if(!message)setDraft(null);}
  return <Modal title="Быстрые команды" onClose={onClose} className="commands-modal"><p className="feature-hint">Команды хранятся локально обычным текстом. Не сохраняйте в них пароли и токены.</p>
    {draft?<form onSubmit={e=>{e.preventDefault();save(draft.id?commands.map(c=>c.id===draft.id?draft:c):[...commands,{...draft,id:crypto.randomUUID()}]);}}><label>Название команды<input autoFocus required maxLength={80} value={draft.name} placeholder="Например, Проверить контейнеры" onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Команда<textarea required maxLength={8000} rows={5} spellCheck={false} value={draft.command} placeholder="docker ps" onChange={e=>setDraft({...draft,command:e.target.value})}/></label><div className="modal-footer"><button type="button" className="secondary" onClick={()=>{setDraft(null);setError('');}}>Назад</button><button className="primary" disabled={busy}>Сохранить команду</button></div></form>:<><div className="command-list">{commands.map(c=><div className="command-row" key={c.id}><div><strong>{c.name}</strong><code>{c.command}</code></div><button className="icon-button" title="Изменить команду" aria-label={`Изменить ${c.name}`} onClick={()=>{setDraft({...c});setError('');}}><Pencil size={15}/></button><button className="icon-button" aria-label={`Удалить ${c.name}`} disabled={busy} onClick={()=>save(commands.filter(x=>x.id!==c.id))}><Trash2 size={15}/></button><button className="icon-button" disabled={!connected} aria-label={`Выполнить ${c.name}`} title={connected?'Посмотреть и выполнить':'Подключитесь к серверу'} onClick={()=>onRun(c.id)}><Play size={17}/></button></div>)}{!commands.length&&<p className="feature-empty">Добавьте команды, которые используете чаще всего.</p>}</div><button className="secondary" disabled={commands.length>=100} onClick={()=>setDraft({id:'',name:'',command:''})}><Plus size={16}/>Добавить команду</button></>}
    {error&&<div role="alert" className="form-error">{error}</div>}</Modal>;
}
type Entry={name:string;directory:boolean;link:boolean;size:number;modified:number};
type Progress={bytes:number;total:number;status:string;name:string;message?:string};
const size=(n:number)=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:n>=1024?`${(n/1024).toFixed(1)} KB`:`${n} B`;
const join=(directory:string,name:string)=>`${directory==='/'?'':directory}/${name}`;
export function SftpPane({id,server,connected,onClose}:{id:string;server:string;connected:boolean;onClose:()=>void}){
  const [directory,setDirectory]=useState('.'),[address,setAddress]=useState('.'),[entries,setEntries]=useState<Entry[]>([]),[selected,setSelected]=useState<Entry|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState<Progress|null>(null);
  const sequence=useRef(0),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;sequence.current++;};},[]);
  async function list(requested:string){const ticket=++sequence.current;setLoading(true);setError('');const result=await window.amber?.sftpList(id,requested);if(!mounted.current||ticket!==sequence.current)return;setLoading(false);if(result?.ok){setDirectory(result.value.path);setAddress(result.value.path);setEntries(result.value.entries);setSelected(null);}else setError(result?.error||'SFTP недоступен');}
  useEffect(()=>{if(connected)list('.');else{sequence.current++;setLoading(false);setBusy(false);setProgress(null);setError('Сессия отключена. Подключитесь снова.');}},[id,connected]);
  useEffect(()=>window.amber?.onEvent(event=>{if(event.id===id&&event.type==='transfer')setProgress(event as unknown as Progress);}),[id]);
  async function transfer(direction:'upload'|'download'){
    if(busy||!connected)return;setBusy(true);setProgress(null);setError('');
    const result=direction==='upload'?await window.amber?.sftpUpload(id,directory):selected?await window.amber?.sftpDownload(id,join(directory,selected.name)):undefined;
    if(!mounted.current)return;setBusy(false);if(result?.ok&&!result.value.canceled){await list(directory);}else if(result&&!result.ok)setError(result.error||'Не удалось передать файл');
  }
  const disabled=!connected||busy||loading;
  return <aside className="sftp-pane" aria-label="Файлы SFTP"><div className="sftp-heading"><div><strong>Файлы SFTP</strong><small>{server} · права SSH-пользователя</small></div><button className="icon-button" aria-label="Закрыть SFTP" onClick={onClose}><X size={17}/></button></div>
    <form className="sftp-path" onSubmit={e=>{e.preventDefault();if(!disabled)list(address);}}><input aria-label="Путь на сервере" value={address} onChange={e=>setAddress(e.target.value)} disabled={disabled}/><button disabled={disabled} title="Открыть путь" aria-label="Открыть путь">→</button></form>
    <div className="sftp-toolbar"><button className="icon-button" aria-label="На уровень выше" disabled={disabled||directory==='/'} onClick={()=>list(directory.split('/').slice(0,-1).join('/')||'/')}><ArrowUp size={16}/></button><button className="icon-button" aria-label="Обновить файлы" disabled={disabled} onClick={()=>list(directory)}><RefreshCw size={15}/></button><button className="secondary" disabled={disabled} onClick={()=>transfer('upload')}><Upload size={14}/>Загрузить</button><button className="icon-button" aria-label="Скачать выбранный файл" disabled={disabled||!selected||selected.directory||selected.link} onClick={()=>transfer('download')}><Download size={17}/></button></div>
    <div className="sftp-files">{entries.map(entry=><button className={`sftp-entry ${selected?.name===entry.name?'selected':''}`} key={entry.name} disabled={disabled} onClick={()=>setSelected(entry)} onDoubleClick={()=>{if(entry.directory)list(join(directory,entry.name));}} title={entry.link?'Символическая ссылка: работа со ссылками пока не поддерживается':entry.directory?'Двойной клик, чтобы открыть папку':'Выберите файл и нажмите скачать'}>{entry.directory?<Folder size={17}/>:entry.link?<Link size={17}/>:<File size={17}/>}<span>{entry.name}</span><small>{entry.directory?'':size(entry.size)}</small></button>)}{loading&&<p className="feature-empty">Читаем папку…</p>}{!loading&&!entries.length&&!error&&<p className="feature-empty">Папка пуста</p>}</div>
    {error&&<div role="alert" className="sftp-error">{error}</div>}{progress&&<div className="transfer-progress"><span>{progress.name}</span><progress value={progress.bytes} max={Math.max(1,progress.total)}/><small>{size(progress.bytes)} / {size(progress.total)} · {progress.status==='complete'?'Готово':progress.status==='error'?'Ошибка':'Передача'}</small></div>}{busy&&<button className="secondary transfer-cancel" onClick={()=>window.amber?.sftpCancel(id)}>Отменить передачу</button>}
  </aside>;
}
